on:
  push:
    branches:
      - master

jobs:
  aoc-cookie:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          COOKIE: ${{ secrets.AOC_COOKIE }}
        run:
          echo "AOC_COOKIE=$COOKIE" > .env
    
  readme-update:
    runs-on: ubuntu-latest
    needs:
      - aoc-cookie
    steps:
      - shell: bash
        run: |
            git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git
            cd Advent-of-Code-Runner
            python -m pip install -e .
            cd ..
            aoc -r -a --readme
