on:
  push:
    branches:
      - master

jobs:
  install-runner:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git
          cd Advent-of-Code-Runner
          pip install -e .

  aoc-cookie:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          COOKIE: ${{ secrets.AOC_COOKIE }}
        run:
          echo "AOC_COOKIE=$COOKIE" > .env
    
  readme-update:
    runs-on: ubuntu-latest
    needs: 
      - install-runner
      - aoc-cookie
    steps:
      - run: aoc -r -a --readme
