on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write

jobs:
  submodule-setup:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: |
          git submodule foreach --recursive python -m pip install -r requirements.txt

  runner-setup:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - shell: bash
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        run: |
          git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git runner
          cd runner
          git submodule update --init --recursive
          python -m pip install -e .
          sudo apt install tesseract-ocr libtesseract-dev
          cd ..
          aoc --no-run

  update-readmes:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    needs:
      - runner-setup
      - submodule-setup
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - shell: bash
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        run: |
          git config user.name ${{ github.actor }}
          aoc -r -a --readme --no-progressbar
          
