on:
  push:
    branches:
      - master

jobs:
  update-readmes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - shell: bash
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        run: |
          git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git runner
          cd runner
          git submodule update --init --recursive
          python -m pip install -e .
          cd ..
          git submodule update --init --recursive
          aoc -r -a --readme --no-progress-bar
