on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  runner-setup:
    uses: brandonhippe/Advent-of-Code-Runner/.github/workflows/setup.yml@main
    with:
      release: readme-viewer-v1.0.0
      token: ${{ github.token }}
      
  update-readmes:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    needs: runner-setup
    steps:
      # Checkout the repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.AOC_PAT }}
          ref: main

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      # Install dependencies for the runner submodule & submodules
      - name: Submodule setup
        run: |
          git submodule foreach --recursive python -m pip install -r requirements.txt

      - name: Configure git username
        run: |
          git config user.name ${{ github.actor }}

      # Run the `aoc` command to update readmes
      - name: Run Code
        run: |
          # aoc -r -a --readme --no-progressbar
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}

      # Commit & push changes
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Ensure submodules are on the correct branch
          git submodule foreach --recursive 'git checkout main || git checkout -b main'
          
          # Commit changes in submodules
          git submodule foreach --recursive 'git add . && git commit -m "Auto-update READMEs" --allow-empty'
          
          # Commit changes in the main repository
          git add .
          git commit -m "Auto-update READMEs" --allow-empty

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AOC_PAT }}
          branch: ${{ github.ref }}
          force: true
