on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readmes:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      # Checkout the repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      # Install dependencies for the runner submodule & submodules
      - run: |
          git submodule foreach --recursive python -m pip install requirements.txt
          git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git runner
          cd runner
          git submodule update --init --recursive
          python -m pip install -e .
          sudo apt install tesseract-ocr libtesseract-dev
        name: Setup

      - run: |
          git config user.name ${{ github.actor }}
        name:
          Git config Username

      # Run the `aoc` command to update readmes
      - run: |
          aoc -r -a --readme --no-progressbar
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        name: Run Code
