on:
  push:
    branches:
      - master

jobs:
  readme-update:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
            AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        run: |
            git clone https://github.com/brandonhippe/Advent-of-Code-Runner.git
            cd Advent-of-Code-Runner
            python -m pip install -e .
            cd ..
            aoc -r -a --readme
