name: Update Readmes

on:
  push:
    branches: 
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:      
  update-readmes:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
    steps:
      # Set up the Advent of Code Runner
      - name: Checkout Advent-of-Code-Runner
        uses: actions/checkout@v4
        with:
          repository: brandonhippe/Advent-of-Code-Runner
          submodules: recursive
          path: runner
          ref: readme-viewer-v1.0.0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install dependencies for the runner submodule & submodules
      - name: Setup Runner
        id: set-runner-path
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          cd runner && python -m pip install -e . && cd ${{ github.workspace }}
          
      # Checkout the repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.AOC_PAT }}
          ref: main
          path: aoc

      # Install dependencies for the runner submodule & submodules
      - name: Submodule setup
        run: |
          git submodule foreach --recursive python -m pip install -r requirements.txt
        working-directory: aoc

      - name: Configure git username
        run: |
          git config user.name ${{ github.actor }}
        working-directory: aoc

      # Run the `aoc` command to update readmes
      - name: Run Code
        run: |
          aoc -r -a --readme --no-progressbar
        env:
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
        working-directory: aoc

      # Commit & push changes
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Ensure submodules are on the correct branch
          git submodule foreach --recursive 'git checkout main || git checkout -b main'
          
          # Commit changes in submodules
          git submodule foreach --recursive 'git add . && git commit -m "Auto-update READMEs [skip actions]" --allow-empty'
          
          # Commit changes in the main repository
          git add .
          git commit -m "Auto-update READMEs [skip actions]" --allow-empty
        working-directory: aoc

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AOC_PAT }}
          branch: ${{ github.ref }}
          directory: aoc
          force: true
